# Generated by Django 6.0.4 on 2026-05-11 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('premium', 'Premium')], max_length=20)),
                ('max_customers', models.IntegerField()),
                ('ai_included', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField()),
                ('doj', models.DateField()),
                ('is_archive', models.BooleanField(default=False)),
                ('primary_certification', models.CharField(choices=[('cert3', 'Certificate III in Fitness'), ('cert4', 'Certificate IV in Fitness'), ('acsm', 'ACSM Certified Personal Trainer'), ('nasm', 'NASM-CPT'), ('ace', 'ACE Personal Trainer'), ('other', 'Other')], max_length=50)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('initial_fitness_level', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archive', models.BooleanField(default=False)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('strength', 'Strength & Conditioning'), ('weight_loss', 'Weight Loss'), ('hiit', 'HIIT & Cardio'), ('flexibility', 'Flexibility & Mobility'), ('sports', 'Sports Performance'), ('rehab', 'Rehabilitation'), ('nutrition', 'Nutrition Coaching'), ('group', 'Group Training')], max_length=50)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trainer')),
            ],
        ),
    ]
