# Generated by Django 6.0.4 on 2026-05-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_subscription_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='experience',
            field=models.CharField(max_length=20),
        ),
    ]
