# Generated by Django 6.0.4 on 2026-05-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_trainer_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='primary_certification',
            field=models.CharField(blank=True, choices=[('cert3', 'Certificate III in Fitness'), ('cert4', 'Certificate IV in Fitness'), ('acsm', 'ACSM Certified Personal Trainer'), ('nasm', 'NASM-CPT'), ('ace', 'ACE Personal Trainer'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
