# Generated by Django 6.0.4 on 2026-05-11 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmark_value', models.PositiveIntegerField()),
                ('progress_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_progress', to='users.client')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_progress', to='training.exercise')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='users.trainer')),
            ],
            options={
                'ordering': ['-progress_date'],
            },
        ),
    ]
