# Generated by Django 6.0.4 on 2026-05-11 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('strength_training', 'Strength Training'), ('hiit_cardio', 'HIIT & Cardio'), ('flexibility_mobility', 'Flexibility & Mobility'), ('weight_loss', 'Weight Loss'), ('consultation', 'Consultation')], max_length=50)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('duration', models.PositiveIntegerField(choices=[(60, '60 Minutes'), (90, '90 Minutes'), (120, '120 Minutes')], default=60)),
                ('repeat', models.CharField(choices=[('none', 'No Repeat'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.client')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.trainer')),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
    ]
